cmd/manager/main.go
pkg/controller/velero/velero.go
pkg/velero/crds.go

We are trying to watch resources that haven't been provisioned:
```
{"level":"error","ts":1566942156.7766368,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"BackupStorageLocation.velero.io","error":"no matches for kind \"BackupStorageLocation\" in version \"velero.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/source/source.go:89\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:122\ngithub.com/openshift/managed-velero-operator/pkg/contro …
```

Provision CRDs before controller startup

---

build/Dockerfile
standard.mk

By copying in just the go.mod and go.sum files, and then running a `go mod download`, we cache the docker layer with the modules and don't need to redownload them each time the code changes. We'll only discard that layer if the go.mod/sum files actually change.

Download and cache go modules in builder container

---

standard.mk

The the project level golang builder is about to be switched to force vendoring mode. This ensures we explicitly maintain the modules mode when building.

Force use of modules

---

deploy/operator.yaml
pkg/controller/velero/velero.go

As infra nodes are existing in all OSD v4 clusters,
velero deployments should be moved to infra nodes.

Move velero deployment to infra nodes

---

cmd/manager/main.go
deploy/credential_request.yaml
pkg/controller/velero/controller.go
pkg/controller/velero/s3.go
pkg/s3/bucket.go
pkg/s3/client.go
pkg/util/platform/platform.go
pkg/util/platform/platform_test.go

If the managed-velero-operator namespace or CR gets deleted,
usually we would have no way of knowing which S3 bucket is associated
with the operator. We would be left with unmanaged S3 resources.
This commit add the ability for managed-velero-operator to recover
from namespace deletion by searching for an existing S3 bucket
associated with velero backups for the cluster on which it is running.
https://issues.redhat.com/browse/OSD-2602

Enable recovery using existing bucket

---

pkg/controller/velero/s3.go
pkg/s3/bucket.go
pkg/s3/bucket_test.go
pkg/s3/client.go

If we use an interface for the S3 client, instead of using the client directly,
we can mock S3 API responses in our unit tests. This commit replaces the `s3.S3` clients
with an interface and adds a couple unit tests using mock API data.
https://issues.redhat.com/browse/OSD-2054

Use an interface for the S3 client

---

pkg/s3/bucket.go
pkg/s3/bucket_test.go

This simplifies this code piece down to one API call, and also doesn't exist the function completely if a single bucket errors.

Simplify error handling logic around bucket tags

---

cmd/manager/main.go
pkg/controller/velero/controller.go
pkg/util/platform/platform.go

Follow up to #35 to simplify some references to platformStatus that are no longer needed.
/assign @dak1n1

Clean up unneeded platformStatus references

---

build/Dockerfile
standard.mk

Currently image building is failing with the following:
```
STEP 13: ENV OPERATOR_PATH=/go/src/github.com/openshift/managed-velero-operator OPERATOR_BIN=managed-velero-operator USER_UID=1001 USER_NAME=managed-velero-operator
STEP 14: COPY --from=builder ${OPERATOR_PATH}/build/_output/bin/${OPERATOR_BIN} /usr/local/bin/${OPERATOR_BIN}
error: build error: error dry-running "COPY --from=builder ${OPERATOR_PATH}/build/_output/bin/${OPERATOR_BIN} /usr/local/bin/${OPERATOR_BIN}": no files found matching "/var/lib/containers/storage/overlay/e510bc260364c86e7210deccc8cd369fd5ae4ff06a8b9d9c50fd5080c2455b00/merged/build/_output/bin": no such file or directory
```
This should fix it up. We don't need to be in the gopath as we are using modules and are building in go1.13

Fix image building

---

cmd/manager/main.go
pkg/controller/velero/controller.go
pkg/controller/velero/velero.go
pkg/storage/constants/constants.go
pkg/storage/s3/bucket_test.go
pkg/storage/s3/s3.go
pkg/storage/storage.go

- Correct the import alias for metav1
- Extract some constants into it's own package so they can be reused
- Move InfraName into the driver, as it's used in different places and is a common configuration piece
- Fix bug where reconcile loop isn't being exited correctly and requeued. We should always requeue after storage reconcile, as there is still the step of provisioning velero to do.

Follow ups from Storage Driver refactor

---

pkg/controller/velero/controller.go
pkg/controller/velero/velero.go
pkg/storage/base/base.go
pkg/storage/gcs/bucket_test.go
pkg/storage/gcs/gcs.go
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go
pkg/storage/storage.go

This adds a `driver` field to the `ReconcileVelero` struct (initialized during the reconcile loop) so that `reconcileVelero()` can access it.
Also substantially refactors the storage driver methods, adding (in OOP terms) a base class with inherited methods.
Most if not all of the platform-specific logic is now encapsulated in the platform-specific drivers.
Sorry for all the commits, but they're mostly small and gradual.

Storage driver refactoring

---

hack/generate-operator-bundle.py

The "replaces" field on the CSV currently doesn't populate correctly because there is no previous version to refer to. This changes the generator to only include that field is a previous version was provided.

Only include "replaces:" field if a previous version was provided

---

hack/generate-operator-bundle.py

The 'required CRDs' portion of the CSV is optional and I suspect it is what is blocking me from creating an InstallPlan when testing this deployment.  Additional details on this field are here: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#required-crds

Removing the optional 'required CRDs' entry

---

hack/olm-registry/olm-artifacts-template.yaml

This indents the `name` and `namespace` fields for the velero service account resource.

Fix indentation on serviceaccount name in old-artifacts-template.yaml

---

hack/app_sre_create_image_catalog.sh

The recent migration from saasherder to app-interface means that create_image_catalog scripts will need to check for the latest deployed hash in a new location. This PR updates the URL and yq command to find the hash deployed to production in the new yaml format.

Update create_image_catalog script to check app-interface for latest deployed prod hash

---

hack/olm-registry/olm-artifacts-template.yaml

Update the apiVersion for the selectorsyncset to 'hive.openshift.io/v1' so that can be applied to the new v4 hive shards.

 Use 'hive.openshift.io/v1' as apiVersion for SSS

---

.ci-operator.yaml

This doesn't do anything yet, but will be used for https://docs.ci.openshift.org/help/ci-operator#buildroot

Add ci-operator build root configuration

---

pkg/apis/managed/v1alpha2/zz_generated.openapi.go

Due to GOPATH settings, this generated differently locally than it does in CI, causing failures once we started using `make validate`.

Regenerate openapi

---

Makefile

https://github.com/openshift/release/pull/13776 standardized prow to use boilerplate's target names for CI jobs, so we no longer need to alias `lint` to `verify`.

Remove temporary nonstandard make targets

---

pkg/velero/crds.go

ref https://github.com/openshift/managed-velero-operator/pull/132#discussion_r693180057
This stanza was removed incorrectly. Right now the CRDs are being updated each time the container boots, no matter if it's needed or not. This fixes that comparison.
/assign @boranx

Replace conversion spec modifications

---

build/Dockerfile

Because the micro image doesn't has root CA files, I see the following errors on stg env:
```
{"level":"error","ts":1646361657.3095574,"logger":"controller.velero-controller","msg":"Reconciler error","name":"cluster","namespace":"openshift-velero","error":"RequestError: send request failed\ncaused by: Get \"https://s3.amazonaws.com/\": x509: certificate signed by unknown authority","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227"}
```

We need use the ubi minimal image, since micro does not has root CA

---

deploy/operator.yaml
deploy/trusted_ca_bundle_configmap.yaml

When debugging a cluster, found that some calls via the AWS SDK weren't using a trusted CA bundle. This should allow it for the operator.

Use trusted CA when accessing urls

---

pkg/controller/velero/velero.go

Getting perpetual reconcile of the metrics service:
```
{"level":"info","ts":1650397714.250771,"logger":"controller_velero","msg":"Updating Service","Request.Namespace":"openshift-velero","Request.Name":"cluster","foundService.Spec":{"ports":[{"name":"metrics","protocol":"TCP","port":8085,"targetPort":8085}],"selector":{"component":"velero","deploy":"velero"},"clusterIP":"172.30.49.148","clusterIPs":["172.30.49.148"],"type":"ClusterIP","sessionAffinity":"None","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","internalTrafficPolicy":"Cluster"},"service.Spec":{"ports":[{"name":"metrics","protocol":"TCP","port":8085,"targetPort":8085}],"selector":{"component":"velero","deploy":"velero"},"clusterIP":"172.30.49.148","type":"ClusterIP","sessionAffinity":"None"}}
```
This corrects this by …

Fix reconcile of metrics service

---

deploy/operator.yaml
hack/olm-registry/olm-artifacts-template.yaml
pkg/controller/velero/velero.go

#143 added this to the deployment.yaml, but that didn't actually get consumed by the subscription. This adds the volumes to the subscription and velero deployment

Add trusted-ca bundle to subscription and to velero deployment

---

.github/dependabot.yml

Disables dependabot for boilerplate, as we update this via other means

Disable dependabot for boilerplate

---

.github/dependabot.yml

Got the application name wrong. Confirmed in logs:
```
updater | INFO <job_523659470> Checking if app-sre/boilerplate image-v2.3.2 needs updating
proxy | 2022/11/23 16:27:52 [020] GET https://quay.io:443/v2/app-sre/boilerplate/tags/list
proxy | 2022/11/23 16:27:52 [020] 200 https://quay.io:443/v2/app-sre/boilerplate/tags/list
updater | INFO <job_523659470> Latest version is image-v3.0.2
updater | INFO <job_523659470> Pull request already exists for app-sre/boilerplate with latest version image-v3.0.2
```
So hopefully this will now ignore it
Also changes the frequency to weekly

Fix boilerplate image name and change cadence

---

cmd/manager/main.go

Noticed in [OSD-14249](https://issues.redhat.com//browse/OSD-14249), `apiextensions.k8s.io/v1beta1` was [removed in K8s v1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/) and no longer served.
It's only usage in the operator codebase was on startup when registering it with the operator's scheme. In `pkg/velero/crds.go` it had been using the apiextensions/v1 api already anyway

Remove `apiextensions.k8s.io/v1beta1` usage

---

controllers/velero/velero.go

Fixes a simple linting error. gosec thinks this might be a hardcoded credential, but it's just the name of the credentials request object.

Fix linting error

---

main.go

SessionAffinity and Type should be set on service generation but are not. This means it will run a no-op update every time operator boots. This isn't a huge deal, but this small change fixes it.

Set two service settings that should be set on generation

---

hack/olm-registry/olm-artifacts-template.yaml

* Restricted SCC enforcement will be added with OCP 4.14
* Updating the catalogsource to allow the operator to get deployed
Jira: [OSD-15615](https://issues.redhat.com//browse/OSD-15615)

Make catalogsource c ompatible with restricted SCC enforcement

---

controllers/velero/velero.go

This field is thrashing because the old "serviceAccount" field is deprecated and we should be using "serviceAccountName". This new field has been around for some time.

Use non-deprecated serviceAccountName field

---

controllers/velero/velero.go

Follow up to #179, as apparently you need to set both if you want a deepequal to work as they are aliases of each other.

Set deprecated serviceAccount field too

---

controllers/velero/velero.go
go.mod
version/version.go

Slight cleanup to use the images from registry.redhat.io as opposed to quay.io/konveyor

Use registry.redhat.io images

---

hack/olm-registry/olm-artifacts-template.yaml

Lets make sure MVO (Managed Velero Operator) is not deployed on OSD clusters running on GCP with WIF (Workload Identity Federation) enabled.
WIF is the GCP equivalent of AWS STS; both are implementing OAuth 2.0. Our policy in that managed clusters should only deploy base operators (i.e. operators that come with OCP) when OAuth 2.0 is in use; indeed we want to keep to a minimal the actions eventually performed by the cluster on the customer cloud provider account when this authentication scheme is in use.
This excludes MVO which is:
- Not a "base" operator, that is to say not an operator bundled with OCP
- Accessing the customer cloud provider
PR is linked to this one: https://github.com/openshift/managed-cluster-config/pull/2188

OSD-20975: Not deploying MVO on GCP WIF clusters

---

hack/olm-registry/olm-artifacts-template.yaml

We are working on a SPIKE to figure out why we continue to have operator install conflicts between HIVE and OLM.
It was suggested that we try changing the default apply mode to `CreateOrUpdate`. 
By default hive will perform the equivalent of a `kubectl apply` when syncing a SSS. Swapping to the `CreateOrUpdate` mode will update hive to perform a `kubectl patch` - and this will hopefully prevent the issues we've been seeing. 
(A in depth explanation can be found here: https://issues.redhat.com/browse/HIVE-2666?focusedId=26162937&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26162937 )
As this issue is not easily reproduced we would like to deploy this change to our non-production clusters and validate if things improve then re-evaluate if we will be …

Set applyBehavior to CreateOrUpdate

---

hack/olm-registry/olm-artifacts-template.yaml

This is a follow up to the change we made in https://github.com/openshift/managed-velero-operator/pull/228 
We want to make sure that changing to `CreateOrUpdate` mode still works as expected when we make changes to the `Template` that creates the `SelectorSyncSet` that will be sync'ed by Hive. 
This change WILL be reverted after we validate in stage, and I'll make sure everything is cleaned up so there are no traces. We have no plans on including this in the production promotion. 
[OSD-28836](https://issues.redhat.com/browse/OSD-28836)

Create test change to audit CreateOrUpdate behavior

---

hack/olm-registry/olm-artifacts-template.yaml

As planned, this PR is to revert the changes we made in https://github.com/openshift/managed-velero-operator/pull/229 so we can observe how `CreateOrUpdate` mode handles removing resources. 
[OSD-28836](https://issues.redhat.com/browse/OSD-28836)

Revert - Create test change to audit CreateOrUpdate behavior

---

go.mod

Updating MVO deps as per openshift 4.18
Fix: https://issues.redhat.com/browse/SREP-157

SREP-157: Deps upgrade as per ocp 4.18
