standard.mk

https://savannah.gnu.org/bugs/?func=detailitem&item_id=10593

Use gomodules in subshell

---

pkg/s3/bucket.go

A new generic, reusable, function for tagging buckets.

Creating tags is now a generic function that can be reused in the future should it be needed.

---

standard.mk

Embed fix for https://github.com/openshift/release/pull/6377 in this repo

Unset GOFLAGS in Makefile

---

pkg/controller/velero/velero.go

@cblecker 
Could you help review?

use chinese mirror for the veleo image in AWS China

---

pkg/controller/velero/velero.go

use the default partitionID for the region which defined in the aws sdk

---

cmd/manager/main.go
deploy/role.yaml
go.mod
pkg/controller/velero/velero.go

Create Service and ServiceMonitor so that metrics can be scraped

veleroDeployment: Create a Service and ServiceMonitor

---

deploy/role.yaml

Fix role to reference correct renamed role

Fix CRD name in role

---

go.mod
go.sum
pkg/storage/s3/s3.go

These were using the incorrect logger

Fix some log lines

---

deploy/credential_request_aws.yaml
pkg/storage/s3/bucket.go
pkg/storage/s3/bucket_test.go
pkg/storage/s3/client.go
pkg/storage/s3/s3.go

Fixes https://issues.redhat.com/browse/OSD-3255

Only fetch bucket tags for buckets in cluster region

---

.codecov.yml
hack/codecov.sh
standard.mk

None of this is running anywhere yet, but this is a prerequisite for getting codecov set up on this repo.

Add scripts for measuring code coverage

---

README.md

Updated README with details on how to test, requirements, and what the operator does.

Expand README.md to include more details

---

hack/codecov.sh

Fix uploader script

---

pkg/velero/crds_test.go

Add test for InstallVeleroCRDs

---

.gitignore
hack/codecov.sh

Found out we are tracking coverage properly, as any files without tests at all won't have coverage included.

More coverage test fixes

---

README.md
hack/codecov.sh

This fixes a variable we pass up in coverage reports, as well as adds some badges to the README

Coverage reporting fix + README badges

---

config/templates/managed-velero-operator-csv-template.yaml
hack/app_sre_build_deploy.sh
hack/app_sre_create_image_catalog.sh
hack/app_sre_pr_check.sh
hack/generate-operator-bundle.py
hack/olm-registry/olm-artifacts-template.yaml
hack/validate_yaml.py

This adds the required templates and scripts for the managed-velero-operator to be deployed via the app-sre pipeline.

Adding files required for app-sre pipeline

---

pkg/storage/s3/bucket_test.go

...mainly to check whether [generated coverage postsubmit](https://github.com/openshift/release/pull/12445) works.

Increase test coverage

---

go.mod
go.sum
pkg/controller/velero/velero.go

https://github.com/vmware-tanzu/velero/releases/tag/v1.5.2

Upgrade velero to 1.5.2

---

pkg/controller/velero/velero.go

https://issues.redhat.com/browse/OSD-7047
Moves from docker images to quay images for velero, velero-plugin-for-aws and velero-plugin-for-gcp. Also removed bit related to AWS China

Use quay velero repos

---

pkg/controller/velero/velero.go

Reverts openshift/managed-velero-operator#126

Revert "Use quay velero repos"

---

go.mod
go.sum
pkg/controller/velero/velero.go
pkg/velero/crds.go
pkg/velero/crds_test.go

Additional fix: https://issues.redhat.com/browse/OSD-7598

fix: update installed crds programmatically

---

pkg/controller/velero/velero.go

fixes [OSD-7047](https://issues.redhat.com/browse/OSD-7047)
This eliminates the dependency on docker hub for pulling the velero images

Use konveyor images instead of docker.io

---

deploy/operator.yaml
hack/olm-registry/olm-artifacts-template.yaml
pkg/controller/velero/velero.go

In #145, the defaultMode for the configmap was removed. This re-adds it.

Set defaultMode for configmap

---

.github/dependabot.yml
build/Dockerfile

Adds a dependabot configuration to automatically update the UBI base image

Add dependabot configuration for dockerfile updates

---

OWNERS

remove achvatal from owners

---

controllers/velero/velero.go
controllers/velero/velero_test.go
controllers/velero/veleroinstall_controller.go
pkg/velero/crds.go
pkg/velero/crds_test.go

corrects the linting errors that are showing up in https://github.com/openshift/managed-velero-operator/pull/237

Correct some linting issues
